<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZooM</title>
    <meta name="description" content="mise en place de la fonctionalitée de zoom depuis des miniatures;">
    <link rel="stylesheet" href="themes/dark/css/normalize.css">
    <link rel="stylesheet" href="themes/dark/css/styles.css">
    <link rel="stylesheet" href="themes/dark/css/animate.css">
</head>
<body>
    <header class="banner">
        <a class="site-logo" href="./index.html">ZooM</a>
        <p class="site-description">Miniatures et effet de Zoom</p>
        <nav class="banner-nav">
            <a class="is-active" href="index.php">Une seule galerie</a>
            <a class="" href="galleries.php">Toutes les galeries</a>
        </nav>
    </header>
    <main>
        <nav class="choice-gallery-nav">
            <?php foreach($galleries as $gallerie) :?>
                <a data-gallery="<?= htmlspecialchars($gallerie) ?>" class="choice-gallery-a" href="?galerie=<?= htmlspecialchars($gallerie) ?>"><?= htmlspecialchars($gallerie) ?></a>
            <?php endforeach;?>
        </nav>

    <h1 class="title"><?= $media; ?></h1>
        
    <section class="gallery-container zoom ajax">
        <ul class="gallery" id="gallery">
        <?php foreach($gallery as $image) : ?>
            <li class="imglist"><img src="<?= $image['src_thumbnails'] ?>" data-src="<?= $image['src'] ?>" class="thumb-img" alt="<?= $image['alt'] ?>"></li>
        <?php endforeach; ?>
        </ul>

        <div class="preview" id="preview">
        </div>
    </section>

    </main>
    <script src="js/ajax-lazy.js"></script>
</body>
</html>