<!DOCTYPE html>
<html lang="fr" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZooM</title>
    <meta name="description" content="mise en place de la fonctionalitée de zoom depuis des miniatures;">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="themes/dark/css/normalize.css">
    <link rel="stylesheet" href="themes/dark/css/styles.css">
</head>

<body>
    <nav class="choice-gallery-nav">
        <?php foreach ($galleries as $gallerie) : ?>
            <a class="choice-gallery-a" href="?galerie=<?= htmlspecialchars($gallerie) ?>"><?= htmlspecialchars($gallerie) ?></a>
        <?php endforeach; ?>
    </nav>

    <main>
        <section class="gallery-container">
            <h1 class="title"><?= htmlspecialchars($gallery) ?></h1>
            <div class="zoom" id="<?= htmlspecialchars($gallery) ?>">
                <ul class="gallery">
                    <?php foreach ($list_gallery as $image) : ?>
                        <li title="Cliquer pour zoomer" class="list">
                            <img 
                            data-src="<?= strip_tags($image['src']) ?>" 
                            src="<?= strip_tags($image['src_thumbnails']) ?>" class="thumbnail" 
                            alt="   
                                <?=
                                    strip_tags($image['alt']);
                                ?>
                                "
                            >
                        </li>
                    <?php endforeach; ?>
                </ul>
                <!-- <figure class="preview">
                    <img 
                    class="picture" 
                    src="<?= strip_tags($list_gallery[0]['src']) ?>" 
                    alt=""
                    >
                    <figcaption class="description"><?= strip_tags($list_gallery[0]['alt']) ?></figcaption>
                </figure> -->
            </div>
        </section>
    </main>
    <script src="js/zoom.js"></script>
</body>

</html>