<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZooM</title>
    <meta name="description" content="mise en place de la fonctionalitée de zoom depuis des miniatures;">
    <link rel="stylesheet" href="themes/dark/css/normalize.css">
    <link rel="stylesheet" href="themes/dark/css/styles.css">
    <link rel="stylesheet" href="themes/dark/css/animate.css">

</head>
<body>
    <header class="banner">
        <a class="site-logo" href="./index.html">ZooM</a>
        <p class="site-description">Miniatures et effet de Zoom</p>
        <nav class="banner-nav">
        <a class="" href="index.php">Une seule galerie</a>
            <a class="is-active" href="galleries.php">Toutes les galeries</a>
        </nav>
    </header>
    <main>
        <?php foreach($lazy_galleries as $index => $lazy_gallery) : ?>
            <h1 class="title"><?= $index; ?></h1>
            <section class="gallery-container zoom <?= $index; ?>">
                <ul class="gallery" id="gallery">
                <?php foreach($lazy_gallery as $image) : ?>
                    <li class="imglist"><img tabindex="0" src="<?= $image['src_thumbnails'] ?>" data-src="<?= $image['src'] ?>" class="thumb-img" alt="<?= $image['alt'] ?>"></li>
                <?php endforeach; ?>
                </ul>

                <div class="preview" id="preview">
                </div>
            </section>
	    <?php endforeach ?>

    </main>
    <script src="js/zoom.js"></script>
</body>
</html>