<section>
    <form action="delete.php" method="POST">
        <table>
            <caption>Liste de contacts stockés</caption>
            <thead>
                <tr>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Courriel</th>
                    <th>Téléphone</th>
                    <th>Delete</th>
                    <th>Modifier</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($contacts as $index => $contact) : ?>
                    <tr>
                        <?php for ($i = 0; $i < count($contact); $i++) : ?>
                            <td><?= $contact[$i]; ?></td>
                        <?php endfor; ?>
                        <td>
                            <input
                                name="todelete[]"
                                value="<?=$index; ?>" 
                                type="checkbox" 
                                aria-label="Supprimer le contact">
                        </td>
                        <td>
                            <a href="edit.php?index=<?= $index ?>">Modifier</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <input type="submit" value="Supprimer le(s) contact(s) selectionné(s)">
    </form>
</section>