<!DOCTYPE html>
<html lang="fr" dir="ltr">
   <head>
      <meta charset="UTF-8">
      <title>L'élément figure</title>
      <meta name="description" content="Structurer une illustration avec la balise de regroupement figure et sa légende figcaption">
      <link href="themes/theme1/figure.css" rel="stylesheet">
   </head>
   <body>

      <header>
         <a href="video.html">
            <h1>Zoom</h1>
            <p></p>
         </a>
      </header>

		<main>
        	<div class="gallery">
				<img src="img/tanjiro.jpg" class="img"><!--
				--><img src="img/nezuko.jpg" class="img"><!--
				--><img src="img/zenitsu.jpg" class="img"><!--
				--><img src="img/inosuke.jpg" class="img"><!--
				--><img src="img/all.jpg" class="img"><!--
				--><img src="img/muzan.jpg" class="img">
        	   </figure>
			</div>

			<div>
        	</div>
		  	<script src="js/zoom.js"></script>
		</main>
   </body>
</html>